/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd7b0fca-0b29-4a30-a529-7d24e33ee0ec",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_O5vVpqo9w",
    "aws_user_pools_web_client_id": "7b302ura6unu7iffpf3lgja37q",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://4ljjbxcnfjbxfczfmv3ili6kwu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-crxrprq3mjhuve5aadsmbuvhgq",
    "aws_user_files_s3_bucket": "reactlocal21da63b3eeb3e47589a74d894d449a078122959-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
